package com.gz.ssm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gz.ssm.entity.Student;
import com.gz.ssm.entity.kemu;

public interface kemuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    int insert(kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    int insertSelective(kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    kemu selectByPrimaryKey(Integer id);
    List<kemu> listAll();
    List<kemu> listAllOrder(@Param("searchName")String searchName,@Param("id")int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(kemu record);
}