package com.gz.ssm.dao;

import com.gz.ssm.entity.zjxq;

public interface zjxqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    int insert(zjxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    int insertSelective(zjxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    zjxq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(zjxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(zjxq record);
}