package com.gz.ssm.entity;

import java.io.Serializable;

public class kemu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.hetongh
     *
     * @mbggenerated
     */
    private String hetongh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.leibie
     *
     * @mbggenerated
     */
    private String leibie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.xmjc
     *
     * @mbggenerated
     */
    private String xmjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.xmjl
     *
     * @mbggenerated
     */
    private String xmjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.htje
     *
     * @mbggenerated
     */
    private String htje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.hkbl
     *
     * @mbggenerated
     */
    private String hkbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.gys
     *
     * @mbggenerated
     */
    private String gys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.hwmc
     *
     * @mbggenerated
     */
    private String hwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.danw
     *
     * @mbggenerated
     */
    private String danw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.shul
     *
     * @mbggenerated
     */
    private String shul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.danj
     *
     * @mbggenerated
     */
    private String danj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.htze
     *
     * @mbggenerated
     */
    private String htze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.kprq
     *
     * @mbggenerated
     */
    private String kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.kpje
     *
     * @mbggenerated
     */
    private String kpje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.yif
     *
     * @mbggenerated
     */
    private String yif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.yue
     *
     * @mbggenerated
     */
    private String yue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.fkbl
     *
     * @mbggenerated
     */
    private String fkbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.jhq
     *
     * @mbggenerated
     */
    private String jhq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.jhqk
     *
     * @mbggenerated
     */
    private String jhqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.htzt
     *
     * @mbggenerated
     */
    private String htzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.zk
     *
     * @mbggenerated
     */
    private String zk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.fkfs
     *
     * @mbggenerated
     */
    private String fkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemu.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kemu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    public kemu(Integer id, String hetongh, String leibie, String xmjc, String xmjl, String htje, String hkbl, String gys, String hwmc, String danw, String shul, String danj, String htze, String kprq, String kpje, String yif, String yue, String fkbl, String jhq, String jhqk, String htzt, String zk, String fkfs, String qq) {
        this.id = id;
        this.hetongh = hetongh;
        this.leibie = leibie;
        this.xmjc = xmjc;
        this.xmjl = xmjl;
        this.htje = htje;
        this.hkbl = hkbl;
        this.gys = gys;
        this.hwmc = hwmc;
        this.danw = danw;
        this.shul = shul;
        this.danj = danj;
        this.htze = htze;
        this.kprq = kprq;
        this.kpje = kpje;
        this.yif = yif;
        this.yue = yue;
        this.fkbl = fkbl;
        this.jhq = jhq;
        this.jhqk = jhqk;
        this.htzt = htzt;
        this.zk = zk;
        this.fkfs = fkfs;
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    public kemu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.id
     *
     * @return the value of kemu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.id
     *
     * @param id the value for kemu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.hetongh
     *
     * @return the value of kemu.hetongh
     *
     * @mbggenerated
     */
    public String getHetongh() {
        return hetongh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.hetongh
     *
     * @param hetongh the value for kemu.hetongh
     *
     * @mbggenerated
     */
    public void setHetongh(String hetongh) {
        this.hetongh = hetongh == null ? null : hetongh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.leibie
     *
     * @return the value of kemu.leibie
     *
     * @mbggenerated
     */
    public String getLeibie() {
        return leibie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.leibie
     *
     * @param leibie the value for kemu.leibie
     *
     * @mbggenerated
     */
    public void setLeibie(String leibie) {
        this.leibie = leibie == null ? null : leibie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.xmjc
     *
     * @return the value of kemu.xmjc
     *
     * @mbggenerated
     */
    public String getXmjc() {
        return xmjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.xmjc
     *
     * @param xmjc the value for kemu.xmjc
     *
     * @mbggenerated
     */
    public void setXmjc(String xmjc) {
        this.xmjc = xmjc == null ? null : xmjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.xmjl
     *
     * @return the value of kemu.xmjl
     *
     * @mbggenerated
     */
    public String getXmjl() {
        return xmjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.xmjl
     *
     * @param xmjl the value for kemu.xmjl
     *
     * @mbggenerated
     */
    public void setXmjl(String xmjl) {
        this.xmjl = xmjl == null ? null : xmjl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.htje
     *
     * @return the value of kemu.htje
     *
     * @mbggenerated
     */
    public String getHtje() {
        return htje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.htje
     *
     * @param htje the value for kemu.htje
     *
     * @mbggenerated
     */
    public void setHtje(String htje) {
        this.htje = htje == null ? null : htje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.hkbl
     *
     * @return the value of kemu.hkbl
     *
     * @mbggenerated
     */
    public String getHkbl() {
        return hkbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.hkbl
     *
     * @param hkbl the value for kemu.hkbl
     *
     * @mbggenerated
     */
    public void setHkbl(String hkbl) {
        this.hkbl = hkbl == null ? null : hkbl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.gys
     *
     * @return the value of kemu.gys
     *
     * @mbggenerated
     */
    public String getGys() {
        return gys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.gys
     *
     * @param gys the value for kemu.gys
     *
     * @mbggenerated
     */
    public void setGys(String gys) {
        this.gys = gys == null ? null : gys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.hwmc
     *
     * @return the value of kemu.hwmc
     *
     * @mbggenerated
     */
    public String getHwmc() {
        return hwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.hwmc
     *
     * @param hwmc the value for kemu.hwmc
     *
     * @mbggenerated
     */
    public void setHwmc(String hwmc) {
        this.hwmc = hwmc == null ? null : hwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.danw
     *
     * @return the value of kemu.danw
     *
     * @mbggenerated
     */
    public String getDanw() {
        return danw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.danw
     *
     * @param danw the value for kemu.danw
     *
     * @mbggenerated
     */
    public void setDanw(String danw) {
        this.danw = danw == null ? null : danw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.shul
     *
     * @return the value of kemu.shul
     *
     * @mbggenerated
     */
    public String getShul() {
        return shul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.shul
     *
     * @param shul the value for kemu.shul
     *
     * @mbggenerated
     */
    public void setShul(String shul) {
        this.shul = shul == null ? null : shul.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.danj
     *
     * @return the value of kemu.danj
     *
     * @mbggenerated
     */
    public String getDanj() {
        return danj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.danj
     *
     * @param danj the value for kemu.danj
     *
     * @mbggenerated
     */
    public void setDanj(String danj) {
        this.danj = danj == null ? null : danj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.htze
     *
     * @return the value of kemu.htze
     *
     * @mbggenerated
     */
    public String getHtze() {
        return htze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.htze
     *
     * @param htze the value for kemu.htze
     *
     * @mbggenerated
     */
    public void setHtze(String htze) {
        this.htze = htze == null ? null : htze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.kprq
     *
     * @return the value of kemu.kprq
     *
     * @mbggenerated
     */
    public String getKprq() {
        return kprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.kprq
     *
     * @param kprq the value for kemu.kprq
     *
     * @mbggenerated
     */
    public void setKprq(String kprq) {
        this.kprq = kprq == null ? null : kprq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.kpje
     *
     * @return the value of kemu.kpje
     *
     * @mbggenerated
     */
    public String getKpje() {
        return kpje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.kpje
     *
     * @param kpje the value for kemu.kpje
     *
     * @mbggenerated
     */
    public void setKpje(String kpje) {
        this.kpje = kpje == null ? null : kpje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.yif
     *
     * @return the value of kemu.yif
     *
     * @mbggenerated
     */
    public String getYif() {
        return yif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.yif
     *
     * @param yif the value for kemu.yif
     *
     * @mbggenerated
     */
    public void setYif(String yif) {
        this.yif = yif == null ? null : yif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.yue
     *
     * @return the value of kemu.yue
     *
     * @mbggenerated
     */
    public String getYue() {
        return yue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.yue
     *
     * @param yue the value for kemu.yue
     *
     * @mbggenerated
     */
    public void setYue(String yue) {
        this.yue = yue == null ? null : yue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.fkbl
     *
     * @return the value of kemu.fkbl
     *
     * @mbggenerated
     */
    public String getFkbl() {
        return fkbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.fkbl
     *
     * @param fkbl the value for kemu.fkbl
     *
     * @mbggenerated
     */
    public void setFkbl(String fkbl) {
        this.fkbl = fkbl == null ? null : fkbl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.jhq
     *
     * @return the value of kemu.jhq
     *
     * @mbggenerated
     */
    public String getJhq() {
        return jhq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.jhq
     *
     * @param jhq the value for kemu.jhq
     *
     * @mbggenerated
     */
    public void setJhq(String jhq) {
        this.jhq = jhq == null ? null : jhq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.jhqk
     *
     * @return the value of kemu.jhqk
     *
     * @mbggenerated
     */
    public String getJhqk() {
        return jhqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.jhqk
     *
     * @param jhqk the value for kemu.jhqk
     *
     * @mbggenerated
     */
    public void setJhqk(String jhqk) {
        this.jhqk = jhqk == null ? null : jhqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.htzt
     *
     * @return the value of kemu.htzt
     *
     * @mbggenerated
     */
    public String getHtzt() {
        return htzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.htzt
     *
     * @param htzt the value for kemu.htzt
     *
     * @mbggenerated
     */
    public void setHtzt(String htzt) {
        this.htzt = htzt == null ? null : htzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.zk
     *
     * @return the value of kemu.zk
     *
     * @mbggenerated
     */
    public String getZk() {
        return zk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.zk
     *
     * @param zk the value for kemu.zk
     *
     * @mbggenerated
     */
    public void setZk(String zk) {
        this.zk = zk == null ? null : zk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.fkfs
     *
     * @return the value of kemu.fkfs
     *
     * @mbggenerated
     */
    public String getFkfs() {
        return fkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.fkfs
     *
     * @param fkfs the value for kemu.fkfs
     *
     * @mbggenerated
     */
    public void setFkfs(String fkfs) {
        this.fkfs = fkfs == null ? null : fkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemu.qq
     *
     * @return the value of kemu.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemu.qq
     *
     * @param qq the value for kemu.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hetongh=").append(hetongh);
        sb.append(", leibie=").append(leibie);
        sb.append(", xmjc=").append(xmjc);
        sb.append(", xmjl=").append(xmjl);
        sb.append(", htje=").append(htje);
        sb.append(", hkbl=").append(hkbl);
        sb.append(", gys=").append(gys);
        sb.append(", hwmc=").append(hwmc);
        sb.append(", danw=").append(danw);
        sb.append(", shul=").append(shul);
        sb.append(", danj=").append(danj);
        sb.append(", htze=").append(htze);
        sb.append(", kprq=").append(kprq);
        sb.append(", kpje=").append(kpje);
        sb.append(", yif=").append(yif);
        sb.append(", yue=").append(yue);
        sb.append(", fkbl=").append(fkbl);
        sb.append(", jhq=").append(jhq);
        sb.append(", jhqk=").append(jhqk);
        sb.append(", htzt=").append(htzt);
        sb.append(", zk=").append(zk);
        sb.append(", fkfs=").append(fkfs);
        sb.append(", qq=").append(qq);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}