package com.gz.ssm.entity;

import java.io.Serializable;

public class zijin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.xmmc
     *
     * @mbggenerated
     */
    private String xmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.skdw
     *
     * @mbggenerated
     */
    private String skdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.yt
     *
     * @mbggenerated
     */
    private String yt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.htje
     *
     * @mbggenerated
     */
    private String htje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.yif
     *
     * @mbggenerated
     */
    private String yif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.yifbl
     *
     * @mbggenerated
     */
    private String yifbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.yus
     *
     * @mbggenerated
     */
    private String yus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.bc
     *
     * @mbggenerated
     */
    private String bc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.jjqk
     *
     * @mbggenerated
     */
    private String jjqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.id1
     *
     * @mbggenerated
     */
    private String id1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.zftj
     *
     * @mbggenerated
     */
    private String zftj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.zzxqsy
     *
     * @mbggenerated
     */
    private String zzxqsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zijin.sqrq
     *
     * @mbggenerated
     */
    private String sqrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zijin
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zijin
     *
     * @mbggenerated
     */
    public zijin(Integer id, String xmmc, String skdw, String yt, String htje, String yif, String yifbl, String yus, String bc, String jjqk, String bz, String id1, String zftj, String zzxqsy, String sqrq) {
        this.id = id;
        this.xmmc = xmmc;
        this.skdw = skdw;
        this.yt = yt;
        this.htje = htje;
        this.yif = yif;
        this.yifbl = yifbl;
        this.yus = yus;
        this.bc = bc;
        this.jjqk = jjqk;
        this.bz = bz;
        this.id1 = id1;
        this.zftj = zftj;
        this.zzxqsy = zzxqsy;
        this.sqrq = sqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zijin
     *
     * @mbggenerated
     */
    public zijin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.id
     *
     * @return the value of zijin.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.id
     *
     * @param id the value for zijin.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.xmmc
     *
     * @return the value of zijin.xmmc
     *
     * @mbggenerated
     */
    public String getXmmc() {
        return xmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.xmmc
     *
     * @param xmmc the value for zijin.xmmc
     *
     * @mbggenerated
     */
    public void setXmmc(String xmmc) {
        this.xmmc = xmmc == null ? null : xmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.skdw
     *
     * @return the value of zijin.skdw
     *
     * @mbggenerated
     */
    public String getSkdw() {
        return skdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.skdw
     *
     * @param skdw the value for zijin.skdw
     *
     * @mbggenerated
     */
    public void setSkdw(String skdw) {
        this.skdw = skdw == null ? null : skdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.yt
     *
     * @return the value of zijin.yt
     *
     * @mbggenerated
     */
    public String getYt() {
        return yt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.yt
     *
     * @param yt the value for zijin.yt
     *
     * @mbggenerated
     */
    public void setYt(String yt) {
        this.yt = yt == null ? null : yt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.htje
     *
     * @return the value of zijin.htje
     *
     * @mbggenerated
     */
    public String getHtje() {
        return htje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.htje
     *
     * @param htje the value for zijin.htje
     *
     * @mbggenerated
     */
    public void setHtje(String htje) {
        this.htje = htje == null ? null : htje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.yif
     *
     * @return the value of zijin.yif
     *
     * @mbggenerated
     */
    public String getYif() {
        return yif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.yif
     *
     * @param yif the value for zijin.yif
     *
     * @mbggenerated
     */
    public void setYif(String yif) {
        this.yif = yif == null ? null : yif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.yifbl
     *
     * @return the value of zijin.yifbl
     *
     * @mbggenerated
     */
    public String getYifbl() {
        return yifbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.yifbl
     *
     * @param yifbl the value for zijin.yifbl
     *
     * @mbggenerated
     */
    public void setYifbl(String yifbl) {
        this.yifbl = yifbl == null ? null : yifbl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.yus
     *
     * @return the value of zijin.yus
     *
     * @mbggenerated
     */
    public String getYus() {
        return yus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.yus
     *
     * @param yus the value for zijin.yus
     *
     * @mbggenerated
     */
    public void setYus(String yus) {
        this.yus = yus == null ? null : yus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.bc
     *
     * @return the value of zijin.bc
     *
     * @mbggenerated
     */
    public String getBc() {
        return bc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.bc
     *
     * @param bc the value for zijin.bc
     *
     * @mbggenerated
     */
    public void setBc(String bc) {
        this.bc = bc == null ? null : bc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.jjqk
     *
     * @return the value of zijin.jjqk
     *
     * @mbggenerated
     */
    public String getJjqk() {
        return jjqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.jjqk
     *
     * @param jjqk the value for zijin.jjqk
     *
     * @mbggenerated
     */
    public void setJjqk(String jjqk) {
        this.jjqk = jjqk == null ? null : jjqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.bz
     *
     * @return the value of zijin.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.bz
     *
     * @param bz the value for zijin.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.id1
     *
     * @return the value of zijin.id1
     *
     * @mbggenerated
     */
    public String getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.id1
     *
     * @param id1 the value for zijin.id1
     *
     * @mbggenerated
     */
    public void setId1(String id1) {
        this.id1 = id1 == null ? null : id1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.zftj
     *
     * @return the value of zijin.zftj
     *
     * @mbggenerated
     */
    public String getZftj() {
        return zftj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.zftj
     *
     * @param zftj the value for zijin.zftj
     *
     * @mbggenerated
     */
    public void setZftj(String zftj) {
        this.zftj = zftj == null ? null : zftj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.zzxqsy
     *
     * @return the value of zijin.zzxqsy
     *
     * @mbggenerated
     */
    public String getZzxqsy() {
        return zzxqsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.zzxqsy
     *
     * @param zzxqsy the value for zijin.zzxqsy
     *
     * @mbggenerated
     */
    public void setZzxqsy(String zzxqsy) {
        this.zzxqsy = zzxqsy == null ? null : zzxqsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zijin.sqrq
     *
     * @return the value of zijin.sqrq
     *
     * @mbggenerated
     */
    public String getSqrq() {
        return sqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zijin.sqrq
     *
     * @param sqrq the value for zijin.sqrq
     *
     * @mbggenerated
     */
    public void setSqrq(String sqrq) {
        this.sqrq = sqrq == null ? null : sqrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zijin
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xmmc=").append(xmmc);
        sb.append(", skdw=").append(skdw);
        sb.append(", yt=").append(yt);
        sb.append(", htje=").append(htje);
        sb.append(", yif=").append(yif);
        sb.append(", yifbl=").append(yifbl);
        sb.append(", yus=").append(yus);
        sb.append(", bc=").append(bc);
        sb.append(", jjqk=").append(jjqk);
        sb.append(", bz=").append(bz);
        sb.append(", id1=").append(id1);
        sb.append(", zftj=").append(zftj);
        sb.append(", zzxqsy=").append(zzxqsy);
        sb.append(", sqrq=").append(sqrq);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}