package com.gz.ssm.entity;

import java.io.Serializable;

public class zjxq implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.sqb
     *
     * @mbggenerated
     */
    private String sqb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.rq
     *
     * @mbggenerated
     */
    private String rq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.gys
     *
     * @mbggenerated
     */
    private String gys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.gcm
     *
     * @mbggenerated
     */
    private String gcm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.hete
     *
     * @mbggenerated
     */
    private String hete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.yif
     *
     * @mbggenerated
     */
    private String yif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.sqj
     *
     * @mbggenerated
     */
    private String sqj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.zftj
     *
     * @mbggenerated
     */
    private String zftj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.jjcd
     *
     * @mbggenerated
     */
    private String jjcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.xmjl
     *
     * @mbggenerated
     */
    private String xmjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.zg1
     *
     * @mbggenerated
     */
    private String zg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zjxq.zg2
     *
     * @mbggenerated
     */
    private String zg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    public zjxq(Integer id, String sqb, String rq, String gys, String gcm, String hete, String yif, String sqj, String zftj, String jjcd, String xmjl, String zg1, String zg2) {
        this.id = id;
        this.sqb = sqb;
        this.rq = rq;
        this.gys = gys;
        this.gcm = gcm;
        this.hete = hete;
        this.yif = yif;
        this.sqj = sqj;
        this.zftj = zftj;
        this.jjcd = jjcd;
        this.xmjl = xmjl;
        this.zg1 = zg1;
        this.zg2 = zg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    public zjxq() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.id
     *
     * @return the value of zjxq.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.id
     *
     * @param id the value for zjxq.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.sqb
     *
     * @return the value of zjxq.sqb
     *
     * @mbggenerated
     */
    public String getSqb() {
        return sqb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.sqb
     *
     * @param sqb the value for zjxq.sqb
     *
     * @mbggenerated
     */
    public void setSqb(String sqb) {
        this.sqb = sqb == null ? null : sqb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.rq
     *
     * @return the value of zjxq.rq
     *
     * @mbggenerated
     */
    public String getRq() {
        return rq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.rq
     *
     * @param rq the value for zjxq.rq
     *
     * @mbggenerated
     */
    public void setRq(String rq) {
        this.rq = rq == null ? null : rq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.gys
     *
     * @return the value of zjxq.gys
     *
     * @mbggenerated
     */
    public String getGys() {
        return gys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.gys
     *
     * @param gys the value for zjxq.gys
     *
     * @mbggenerated
     */
    public void setGys(String gys) {
        this.gys = gys == null ? null : gys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.gcm
     *
     * @return the value of zjxq.gcm
     *
     * @mbggenerated
     */
    public String getGcm() {
        return gcm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.gcm
     *
     * @param gcm the value for zjxq.gcm
     *
     * @mbggenerated
     */
    public void setGcm(String gcm) {
        this.gcm = gcm == null ? null : gcm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.hete
     *
     * @return the value of zjxq.hete
     *
     * @mbggenerated
     */
    public String getHete() {
        return hete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.hete
     *
     * @param hete the value for zjxq.hete
     *
     * @mbggenerated
     */
    public void setHete(String hete) {
        this.hete = hete == null ? null : hete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.yif
     *
     * @return the value of zjxq.yif
     *
     * @mbggenerated
     */
    public String getYif() {
        return yif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.yif
     *
     * @param yif the value for zjxq.yif
     *
     * @mbggenerated
     */
    public void setYif(String yif) {
        this.yif = yif == null ? null : yif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.sqj
     *
     * @return the value of zjxq.sqj
     *
     * @mbggenerated
     */
    public String getSqj() {
        return sqj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.sqj
     *
     * @param sqj the value for zjxq.sqj
     *
     * @mbggenerated
     */
    public void setSqj(String sqj) {
        this.sqj = sqj == null ? null : sqj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.zftj
     *
     * @return the value of zjxq.zftj
     *
     * @mbggenerated
     */
    public String getZftj() {
        return zftj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.zftj
     *
     * @param zftj the value for zjxq.zftj
     *
     * @mbggenerated
     */
    public void setZftj(String zftj) {
        this.zftj = zftj == null ? null : zftj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.jjcd
     *
     * @return the value of zjxq.jjcd
     *
     * @mbggenerated
     */
    public String getJjcd() {
        return jjcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.jjcd
     *
     * @param jjcd the value for zjxq.jjcd
     *
     * @mbggenerated
     */
    public void setJjcd(String jjcd) {
        this.jjcd = jjcd == null ? null : jjcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.xmjl
     *
     * @return the value of zjxq.xmjl
     *
     * @mbggenerated
     */
    public String getXmjl() {
        return xmjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.xmjl
     *
     * @param xmjl the value for zjxq.xmjl
     *
     * @mbggenerated
     */
    public void setXmjl(String xmjl) {
        this.xmjl = xmjl == null ? null : xmjl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.zg1
     *
     * @return the value of zjxq.zg1
     *
     * @mbggenerated
     */
    public String getZg1() {
        return zg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.zg1
     *
     * @param zg1 the value for zjxq.zg1
     *
     * @mbggenerated
     */
    public void setZg1(String zg1) {
        this.zg1 = zg1 == null ? null : zg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zjxq.zg2
     *
     * @return the value of zjxq.zg2
     *
     * @mbggenerated
     */
    public String getZg2() {
        return zg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zjxq.zg2
     *
     * @param zg2 the value for zjxq.zg2
     *
     * @mbggenerated
     */
    public void setZg2(String zg2) {
        this.zg2 = zg2 == null ? null : zg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zjxq
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sqb=").append(sqb);
        sb.append(", rq=").append(rq);
        sb.append(", gys=").append(gys);
        sb.append(", gcm=").append(gcm);
        sb.append(", hete=").append(hete);
        sb.append(", yif=").append(yif);
        sb.append(", sqj=").append(sqj);
        sb.append(", zftj=").append(zftj);
        sb.append(", jjcd=").append(jjcd);
        sb.append(", xmjl=").append(xmjl);
        sb.append(", zg1=").append(zg1);
        sb.append(", zg2=").append(zg2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}